name: Run Unix

on: [push, pull_request]

jobs:
  RunUnix_15:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [macos-10.15]

    steps:
    # compile and prepare env
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
        architecture: 'x64'
    - name: Install Python Dependencies
      if: (matrix.os == 'ubuntu-18.04')
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y python3-setuptools python3-pygments
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.3.1
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.3
    - name: Compile BrainFlow
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -DWARNINGS_AS_ERRORS=ON -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/installed -DCMAKE_BUILD_TYPE=Release ..
        make -j
        make install
    - name: Fascia Python Markers
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/fascia_emulator_ci.py python3 $GITHUB_WORKSPACE/tests/python/markers.py --board-id 12 --ip-port 7789
