name: Run Android NDK

on: [push, pull_request]

jobs:
  RunAndroid:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Install Ninja
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y ninja-build zip unzip
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: Install NDK
      run: |
        echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT} > /dev/null
    # build for all ABIs
    - name: Compile BrainFlow
      run: |
        for ABI in arm64-v8a armeabi-v7a x86 x86_64; do
          mkdir $GITHUB_WORKSPACE/build-$ABI
          cd $GITHUB_WORKSPACE/build-$ABI
          cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk/21.0.6113669/build/cmake/android.toolchain.cmake -DANDROID_ABI=$ABI -DCMAKE_BUILD_TYPE=Release -DANDROID_NATIVE_API_LEVEL=android-19 ..
          ninja
        done
    - name: Prepare Zip
      run: |
        cd $GITHUB_WORKSPACE/tools
        zip -r jniLibs.zip jniLibs
    - name: Install AWS CLI
      run: sudo -H python -m pip install awscli
    - name: Upload To AWS
      if: ${{ github.event_name == 'push' && github.repository == 'brainflow-dev/brainflow' }}
      run: |
        cd $GITHUB_WORKSPACE/tools
        aws s3 cp jniLibs.zip s3://brainflow/$GITHUB_SHA/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
